# -*- coding: utf-8 -*-
"""
SmartPOS Mini Pro - Dil Dosyası / Language File
Türkçe ve İngilizce çeviri verileri
Turkish and English translation data
"""

LANGUAGES = {
    "tr": {
        "app_title": "SmartPOS Mini Pro",
        "subtitle": "Küçük işletmeler için satış sistemi",
        
        # İlk Kurulum
        "welcome": "Hoş Geldiniz!",
        "select_language": "Lütfen dil seçiniz / Please select language",
        "continue": "Devam Et",
        "setup_complete": "Kurulum tamamlandı!",
        "username": "Kullanıcı Adı:",
        "password": "Şifre:",
        "login": "Giriş Yap",
        "show": "Göster",
        "hide": "Gizle",
        "logout": "Çıkış Yap",
        "confirm_logout": "Çıkış yapmak istediğinize emin misiniz?",
        "confirm_exit": "Uygulamadan çıkmak istediğinize emin misiniz?",
        "exit_title": "Çıkış",
        "language": "Dil:",
        
        # Profil / İşletme
        "profile": "Profil",
        "business_info": "İşletme Bilgileri",
        "company_name": "İşletme Adı:",
        "tax_office": "Vergi Dairesi:",
        "tax_number": "Vergi No:",
        "receipt_footer": "Fiş Alt Yazısı:",
        "change_password": "Şifre Değiştir",
        "current_password": "Mevcut Şifre:",
        "new_password2": "Yeni Şifre:",
        "confirm_password": "Yeni Şifre (Tekrar):",
        "profile_saved": "Profil kaydedildi",
        "password_changed": "Şifre değiştirildi",
        "wrong_password": "Mevcut şifre yanlış!",
        "password_mismatch": "Yeni şifreler uyuşmuyor!",
        
        # Modern POS Arayüzü
        "paid": "Ödenen",
        "money_on_account": "Para Üstü",
        "quick_amounts": "Hızlı Tutar",
        "quick_products": "Hızlı Ürünler",
        "lists": "Listeler",
        "cash_register": "NAKİT",
        "pos_payment": "KREDİ KARTI",
        "open_account": "AÇIK HESAP",
        "fragmented": "PARÇALI",
        "credit_card": "KREDİ KARTI",
        "bank_transfer": "HAVALE",
        "main_list": "ANA",
        "list_1": "LİSTE 1",
        "list_2": "LİSTE 2",
        "list_3": "LİSTE 3",
        "list_4": "LİSTE 4",
        "sales_note": "Satışa dair notlar",
        "sms_receipt": "Fiş SMS gönder",
        "customer_phone": "Telefon (5xxxxxxxxxx)",
        "sms_note": "*Alışveriş fişini SMS ile göndermek için doldurununuz",
        "limit_info": "Limit : ₺ 0.00 - Kalan borcu : ₺ 0.00",
        "complete_sale_btn": "SATIŞ YAP",
        
        # Menü
        "sales": "Satış Yap",
    "products": "Ürün Yönetimi",
    "action_menu": "İşlem Menüsü",
    "menu_hint": "Sol menüden bir işlem seçiniz 👈",
        "users": "Kullanıcı Yönetimi",
        "cariler": "Cari Hesaplar",
        "receipts": "Fişleri Görüntüle / Yazdır",
        "reports": "Raporlar",
        "daily_report": "Günlük Raporu Kaydet",
    # Yeni üst sekmeler
    "stock_mgmt": "Stok Yönetimi",
    "product_mgmt": "Ürün Yönetimi",
    "account_mgmt_menu": "Cari Yönetim",
    "service_expense_mgmt": "Hizmet/Masraf Yönetimi",
    "purchase_mgmt": "Satın Alma Yönetimi",
    "personnel_mgmt": "Personel Yönetimi",
    "warehouse_mgmt": "Depo Yönetimi",
    "cash_mgmt": "Kasa Yönetimi",
    "theme_settings": "Tema Ayarları",
    "theme_select": "Tema Seçimi",
    "dark_theme": "Koyu Tema",
    "light_theme": "Açık Tema",
    "custom_theme": "Özel Tema",
    "bg_color": "Arkaplan Rengi",
    "fg_color": "Yazı Rengi",
    "sidebar_color": "Menü Rengi",
    "card_color": "Kart Rengi",
    "accent_color": "Vurgu Rengi",
    "restart_required": "Değişikliklerin geçerli olması için uygulamayı yeniden başlatın.",
    "pick_color": "Renk Seç",
    "restore_defaults": "Varsayılanlara Dön",
        
        # Ürün Yönetimi
        "product_management": "Ürün Yönetimi",
        "find_product": "Ürün Bul",
        "product_search": "Ürün Arama",
        "search": "Ara:",
        "add": "Ekle",
        "edit": "Düzenle",
        "delete": "Sil",
        "details": "Detaylar",
        "refresh": "Yenile",
        "save": "Kaydet",
        "update_btn": "Güncelle",
        "clear_form": "Formu Temizle",
        "id": "ID",
        "name": "Ad",
        "barcode": "Barkod",
    "barcode_mgmt": "Barkod Yönetimi",
    "current_barcode": "Mevcut Barkod:",
    "new_barcode": "Yeni Barkod:",
    "updated": "Güncellendi",
    "apply": "Uygula",
    "done": "İşlem tamamlandı.",
    "price": "Fiyat",
        "stock": "Stok",
    "unit": "Birim",
    "adet": "Adet",
    "kg": "Kg",
    "product_info": "Ürün Bilgileri",
    "buy_price": "Alış Fiyatı",
    "sale_price": "Satış Fiyatı",
    "product_list": "Ürün Listesi",
    "barcode_mgmt": "Barkod Yönetimi",
    "category_mgmt": "Kategori Yönetimi",
    "category": "Kategori",
    "category_name": "Kategori Adı",
    "category_color": "Renk",
    "add_category": "Kategori Ekle",
    "edit_category": "Kategori Düzenle",
    "delete_category": "Kategori Sil",
    "product_count": "Ürün Sayısı",
    "no_categories": "Henüz kategori eklenmemiş.",
    "see_price": "Fiyat Gör",
    "reprint": "Yazdır\nSatış Saklayınız",
    "select_record": "Bir kayıt seçin.",
    "stock_in": "Stok Giriş",
    "stock_out": "Stok Çıkış",
    "inventory_count": "Envanter Sayımı",
    "cari_list": "Cari Listesi",
    "collection_entry": "Tahsilat Girişi",
    "payment_entry": "Ödeme Girişi",
    "transactions": "Hareketler",
    "service_list": "Hizmet Listesi",
    "add_expense": "Masraf Ekle",
    "expense_report": "Masraf Raporu",
    "supplier_list": "Tedarikçi Listesi",
    "dispatch_entry": "İrsaliye Girişi",
    "invoice_entry": "Fatura Girişi",
    "dispatch_list": "İrsaliye Listesi",
    "invoice_list": "Fatura Listesi",
    "personnel_list": "Personel Listesi",
    "shift_mgmt": "Vardiya Yönetimi",
    "salary_advance": "Maaş/Avans",
    "salary": "Maaş",
    "advance": "Avans",
    "bonus": "Prim",
    "start_time": "Başlangıç Saati",
    "end_time": "Bitiş Saati",
    "working": "Çalışıyor",
    "not_working": "Çalışmıyor",
    "shift_started": "Vardiya başlatıldı",
    "shift_ended": "Vardiya sonlandırıldı",
    "add_payment": "Ödeme Ekle",
    "type": "Tür",
    "invalid_amount": "Geçersiz tutar",
    "warehouse": "Depo",
    "warehouse_list": "Depo Listesi",
    "source_warehouse": "Kaynak Depo",
    "target_warehouse": "Hedef Depo",
    "stock_status": "Stok Durumu",
    "fill_all_fields": "Tüm alanları doldurunuz!",
    "transfer_success": "Transfer başarılı!",
    "transfer": "Transfer",
    "transfer": "Transfer",
    "warehouse_movements": "Depo Hareketleri",
    "cash_movements": "Kasa Hareketleri",
    "cash_closure": "Kasa Devir",
    "cash_report": "Kasa Raporu",
    "sales_report_menu": "Satış Raporu",
    "stock_report_menu": "Stok Raporu",
    "account_report_menu": "Cari Raporu",
    "cash_report_menu": "Kasa Raporu",
    "settings": "Ayarlar",
    "quick_menu_settings": "Hızlı Menü Ayarları",
    "quick_menu_title": "Hızlı Menü Yönetimi",
    "button_text": "Buton Metni",
    "button_price": "Fiyat",
    "list_code": "Liste Kodu",
    "sort_order": "Sıra",
        
        # Kullanıcı Yönetimi
        "user_management": "Kullanıcı Yönetimi",
        "user": "Kullanıcı",
        "role": "Rol",
        
        # Satış
        "sales_screen": "Satış Ekranı",
        "barcode_scanner": "Barkod Okuyucu:",
        "scan_barcode": "Barkodu okutun veya girin",
        "scan_product_placeholder": "Ürün Barkodunu Okutunuz...",
        "product": "Ürün",
        "quantity": "Adet",
        "unit_price": "Birim Fiyat",
        "total": "Toplam ₺",
        "payment_method": "Ödeme Yöntemi",
        "choose_payment": "Ödeme yöntemini seçiniz:",
        "cash": "Nakit",
        "credit_card": "Kredi Kartı",
        "customer_name": "Müşteri Adı:",
        "add_to_cart": "Sepete Ekle",
        "remove_selected": "Seçili Ürünü Kaldır",
        "clear_cart": "Sepeti Temizle",
        "complete_sale": "Satışı Tamamla",
        "receipt_no": "Fiş No:",
        "discount": "İndirim (%):",
        "vat": "KDV (%):",
        "vat_included": "KDV Dahil",
        "subtotal": "Ara Toplam:",
        "grand_total": "Genel Toplam:",
        "cancel_sale": "Satış İptal",
        "recent_receipts": "Son Fişler",
        "cancel_receipt": "Fişi İptal Et",
        "confirm_cancel_receipt": "Bu fişi iptal etmek istiyor musunuz?",
        "cancel_success": "Fiş iptal edildi.",
        "cancel_error": "İptal sırasında hata oluştu.",
        
        # Fişler
        "receipts_title": "Kayıtlı Fişler (PDF)",
        "file": "Dosya",
        "date": "Tarih",
        "open_print": "Aç / Yazdır",
        
        # Raporlar
        "reports_title": "Satış Raporu",
        "start_date": "Başlangıç (YYYY-MM-DD):",
        "end_date": "Bitiş (YYYY-MM-DD):",
        "export_csv": "CSV Dışa Aktar",
        
        # Cari Hesaplar
        "cari_management": "Cari Hesap Yönetimi",
    "cari_info": "Cari Bilgileri",
        "cari_name": "Cari Adı:",
        "phone": "Telefon:",
        "address": "Adres:",
        "balance": "Bakiye:",
        "cari_type": "Tip:",
        "alacakli": "Alacaklı",
        "borclu": "Borçlu",
        "tahsilat": "Tahsilat",
        "odeme": "Ödeme",
        "borc": "Borç",
        "alacak": "Alacak",
        "tutar": "Tutar:",
        "aciklama": "Açıklama:",
        "hareketler": "Hareketler",
        "islem_type": "İşlem",
        "total_alacak": "Toplam Alacak:",
        "total_borc": "Toplam Borç:",
        "add_tahsilat": "Tahsilat Ekle",
        "add_odeme": "Ödeme Ekle",
        
        # Mesajlar
        "warning": "Uyarı",
        "error": "Hata",
        "success": "Başarılı",
        "confirm": "Onay",
        "select_item": "Bir öğe seçin.",
        "login_error": "Kullanıcı adı veya şifre hatalı!",
        "delete_confirm": "silinsin mi?",
        "receipt_created": "Fiş Oluşturuldu",
        "receipt_saved": "Fatura kaydedildi:",
        "report_saved": "Rapor Kaydedildi",
        "thank_you": "Teşekkür ederiz - SmartPOS Mini Pro",
        "copyright": "SmartPOS Mini Pro © 2025",
        "timestamp": "Zaman damgası:",
    "session": "Oturum",
        
        # Dialog
        "add_product": "Ürün Ekle",
        "product_name": "Ürün adı:",
        "price_input": "Fiyat (örn 99.90):",
        "stock_input": "Stok (örn 10):",
        "edit": "Düzenle",
        "new_user": "Yeni Kullanıcı",
        "role_input": "Rol (admin/cashier):",
        "new_password": "Yeni şifre (boş bırak=değişmesin):",
        "duplicate_error": "Bu ürün adı zaten mevcut!",
        "duplicate_user_error": "Bu kullanıcı adı zaten mevcut!",
        "admin_delete_error": "admin kullanıcısı silinemez!",
        "enter_valid": "Geçerli fiyat/stok girin.",
        "customer": "Müşteri",
    "valid_product_qty": "Geçerli ürün ve adet girin.",
    "product_not_found": "Ürün bulunamadı.",
    "insufficient_stock": "Yetersiz stok! (Mevcut: {stock})",
    "barcode_not_found": "Barkod bulunamadı: {barcode}",
    "cart_empty": "Sepet boş.",
    "info": "Bilgi",
    "no_sales_today": "Bugün için satış yok.",
    "open_failed": "Açılamadı:",
    "date_format_warning": "Tarih formatı YYYY-MM-DD olmalı.",
    "daily_report_saved": "Günlük rapor kaydedildi:",
    "csv_receipt_no": "Fiş No",
    "csv_product": "Ürün",
    "csv_qty": "Adet",
    "csv_price": "Fiyat",
    "csv_total": "Toplam",
    "csv_date": "Tarih",
    "special_vat": "Özel KDV",
    "enter_vat_percent": "KDV oranını gir (%):",
    "no_sales_in_range": "Bu aralıkta satış yok.",
    "cari_added": "Cari eklendi",
    "cari_updated": "Cari güncellendi",
    "cari_deleted": "Cari silindi",
    "cari_added_name": "Cari eklendi: {name}",
    "list": "Listele",
    "seq": "Sıra",
    "vat_short": "KDV",

    # Yeni Menü Öğeleri
    "dispatch_entry": "İrsaliye Girişi",
    "invoice_entry": "Fatura Girişi",
    "stock_list": "Stok Listesi",
    "dispatch_entry_coming": "İrsaliye girişi ekranı yakında eklenecek.",
    "invoice_entry_coming": "Fatura girişi ekranı yakında eklenecek.",
    "coming_soon": "Yakında eklenecek.",
    "service_name": "Hizmet Adı",
    "new_service": "Yeni Hizmet",
    "expense_title": "Masraf Başlığı",
    "recent_expenses": "Son Masraflar",
    "saved": "Kaydedildi",
    "confirm_delete": "Silmek istediğinize emin misiniz?",
    "amount": "Tutar",
    "description": "Açıklama",
        
        # PDF Fiş
        "receipt_header": "SMARTPOS MINI PRO - SATIŞ FİŞİ",
        "receipt_customer": "Müşteri:",
        "receipt_date": "Tarih:",
        "receipt_product": "Ürün",
        "receipt_quantity": "Adet",
    "quantity_unit": "Miktar",
        "receipt_price": "Fiyat",
        "receipt_total": "Tutar",
        "receipt_subtotal": "Ara Toplam:",
        "receipt_discount": "İndirim",
        "receipt_vat": "KDV",
        "receipt_grand_total": "Genel Toplam:",
        "receipt_thank_you": "Teşekkür ederiz - SmartPOS Mini Pro",
        
        # Termal Yazıcı
        "print_receipt": "Fiş Yazdır",
        "print_options": "Yazdırma seçeneğini seçin:",
        "thermal_printer": "Termal Yazıcı",
        "no_print": "Yazdırma",
        "printer_setup": "Yazıcı Ayarı",
        "enter_printer_name": "Yazıcı adını girin (Cihazlar ve Yazıcılar'dan bakın):",
        "receipt_printed": "Fiş yazıcıya gönderildi!",
        "print_error": "Yazıcı hatası",
        
        # Diğer
        "confirm_repeat": "Yinele işlemine devam edilsin mi?",
        "yes": "Evet",
        "no": "Hayır",
        "all": "Tümü",
        
        # Rapor Ekleri
        "total_stock": "Toplam Stok",
        "cost_value": "Maliyet Değeri",
        "sales_value": "Satış Değeri",
        "estimated_profit": "Tahmini Kar",
        "total_cost": "Top. Maliyet",
        "total_sales": "Top. Satış",
        "total_receivable_market": "Toplam Alacak (Piyasa)",
        "total_debt_ours": "Toplam Borç (Bizim)",
        "net_status": "Net Durum",
        "we_are_creditor": "(Alacaklıyız)",
        "we_are_debtor": "(Borçluyuz)",
        "status": "Durum",
        "debtor_to_us": "Borçlu (Bize)",
        "creditor_from_us": "Alacaklı (Bizden)",

        # Kasa Raporu
        "cash_report_title": "KASA RAPORU",
        "date_range": "Tarih Aralığı",
        "total_sales_cash": "Toplam Satış (Nakit)",
        "total_collection": "Toplam Tahsilat",
        "total_inflow": "TOPLAM GİRİŞ",
        "total_payment": "Toplam Ödeme",
        "total_expense": "Toplam Masraf",
        "total_outflow": "TOPLAM ÇIKIŞ",
        "net_balance_cap": "NET BAKİYE",
        "report_btn": "Raporla",

        # Kasa Hareket & Devir
        "total_in_lbl": "Giriş",
        "total_out_lbl": "Çıkış",
        "balance_lbl": "Bakiye",
        "date_lbl": "Tarih",
        "end_day_balance": "Gün Sonu Bakiyesi",
        "close_day_btn": "GÜNÜ KAPAT",
        "close_day_success": "tarihli kasa devri başarıyla tamamlandı.\n\nDevir Bakiyesi",
    },
    "en": {
        "app_title": "SmartPOS Mini Pro",
        "subtitle": "Point of Sale System for Small Businesses",
        
        # Initial Setup
        "welcome": "Welcome!",
        "select_language": "Please select language / Lütfen dil seçiniz",
        "continue": "Continue",
        "setup_complete": "Setup completed!",
        "username": "Username:",
        "password": "Password:",
        "login": "Login",
        "show": "Show",
        "hide": "Hide",
        "logout": "Logout",
        "confirm_logout": "Are you sure you want to logout?",
        "confirm_exit": "Are you sure you want to exit the application?",
        "exit_title": "Exit",
        "language": "Language:",
        
        # Profile / Business
        "profile": "Profile",
        "business_info": "Business Information",
        "company_name": "Company Name:",
        "tax_office": "Tax Office:",
        "tax_number": "Tax Number:",
        "receipt_footer": "Receipt Footer:",
        "change_password": "Change Password",
        "current_password": "Current Password:",
        "new_password2": "New Password:",
        "confirm_password": "Confirm Password:",
        "profile_saved": "Profile saved",
        "password_changed": "Password changed",
        "wrong_password": "Current password is incorrect!",
        "password_mismatch": "New passwords do not match!",
        
        # Modern POS Interface
        "paid": "Paid",
        "money_on_account": "Change",
        "quick_amounts": "Quick Amount",
        "quick_products": "Quick Products",
        "lists": "Lists",
        "cash_register": "CASH",
        "pos_payment": "POS",
        "open_account": "OPEN ACCOUNT",
        "fragmented": "FRAGMENTED",
        "credit_card": "CREDIT CARD",
        "bank_transfer": "WIRE TRANSFER",
        "main_list": "MAIN",
        "list_1": "LIST 1",
        "list_2": "LIST 2",
        "list_3": "LIST 3",
        "list_4": "LIST 4",
        "sales_note": "Sales related notes",
        "sms_receipt": "Send receipt via SMS",
        "customer_phone": "Phone (5xxxxxxxxxx)",
        "sms_note": "*Fill in to send receipt via SMS",
        "limit_info": "Limit : ₺ 0.00 - Remaining debt : ₺ 0.00",
        "complete_sale_btn": "COMPLETE SALE",
        
        # Menu
        "sales": "Make Sale",
        "products": "Product Management",
    "action_menu": "Action Menu",
    "menu_hint": "Select an action from the left menu 👈",
        "users": "User Management",
        "cariler": "Accounts",
        "receipts": "View / Print Receipts",
        "reports": "Reports",
        "daily_report": "Save Daily Report",
    # New top sections
    "stock_mgmt": "Stock Management",
    "product_mgmt": "Product Management",
    "account_mgmt_menu": "Account Management",
    "service_expense_mgmt": "Service/Expense Management",
    "purchase_mgmt": "Purchasing Management",
    "personnel_mgmt": "Personnel Management",
    "warehouse_mgmt": "Warehouse Management",
    "cash_mgmt": "Cash Management",
    "theme_settings": "Theme Settings",
    "theme_select": "Select Theme",
    "dark_theme": "Dark Theme",
    "light_theme": "Light Theme",
    "custom_theme": "Custom Theme",
    "bg_color": "Background Color",
    "fg_color": "Text Color",
    "sidebar_color": "Sidebar Color",
    "card_color": "Card Color",
    "accent_color": "Accent Color",
    "restart_required": "Please restart the application for changes to take effect.",
    "pick_color": "Pick Color",
    "restore_defaults": "Restore Defaults",
        
        # Product Management
        "product_management": "Product Management",
        "search": "Search:",
        "add": "Add",
        "edit": "Edit",
        "delete": "Delete",
        "refresh": "Refresh",
        "save": "Save",
        "update_btn": "Update",
        "clear_form": "Clear Form",
        "id": "ID",
        "name": "Name",
        "barcode": "Barcode",
    "barcode_mgmt": "Barcode Management",
    "current_barcode": "Current Barcode:",
    "new_barcode": "New Barcode:",
    "updated": "Updated",
    "apply": "Apply",
    "done": "Operation completed.",
    "price": "Price",
        "stock": "Stock",
    "unit": "Unit",
    "adet": "Piece",
    "kg": "Kg",
    "product_info": "Product Info",
    "buy_price": "Buy Price",
    "sale_price": "Sale Price",
    "product_list": "Product List",
    "barcode_mgmt": "Barcode Management",
    "category_mgmt": "Category Management",
    "category": "Category",
    "category_name": "Category Name",
    "category_color": "Color",
    "add_category": "Add Category",
    "edit_category": "Edit Category",
    "delete_category": "Delete Category",
    "product_count": "Product Count",
    "no_categories": "No categories yet.",
    "see_price": "See Price",
    "reprint": "Print\nSave Sale",
    "select_record": "Select a record.",
    "stock_in": "Stock In",
    "stock_out": "Stock Out",
    "inventory_count": "Inventory Count",
    "cari_list": "Account List",
    "collection_entry": "Collection Entry",
    "payment_entry": "Payment Entry",
    "transactions": "Transactions",
    "service_list": "Service List",
    "add_expense": "Add Expense",
    "expense_report": "Expense Report",
    "supplier_list": "Supplier List",
    "personnel_list": "Personnel List",
    "shift_mgmt": "Shift Management",
    "salary_advance": "Salary/Advance",
    "salary": "Salary",
    "advance": "Advance",
    "bonus": "Bonus",
    "start_time": "Start Time",
    "end_time": "End Time",
    "working": "Working",
    "not_working": "Not Working",
    "shift_started": "Shift started",
    "shift_ended": "Shift ended",
    "add_payment": "Add Payment",
    "type": "Type",
    "invalid_amount": "Invalid amount",
    "warehouse": "Warehouse",
    "warehouse_list": "Warehouse List",
    "source_warehouse": "Source Warehouse",
    "target_warehouse": "Target Warehouse",
    "stock_status": "Stock Status",
    "fill_all_fields": "Please fill all fields!",
    "transfer_success": "Transfer successful!",
    "transfer": "Transfer",
    "transfer": "Transfer",
    "warehouse_movements": "Warehouse Movements",
    "cash_movements": "Cash Movements",
    "cash_closure": "Cash Closure",
    "cash_report": "Cash Report",
    "sales_report_menu": "Sales Report",
    "stock_report_menu": "Stock Report",
    "account_report_menu": "Account Report",
    "cash_report_menu": "Cash Report",
    "settings": "Settings",
    "quick_menu_settings": "Quick Menu Settings",
    "quick_menu_title": "Quick Menu Management",
    "button_text": "Button Text",
    "button_price": "Price",
    "list_code": "List Code",
    "sort_order": "Order",
        
        # User Management
        "user_management": "User Management",
        "user": "User",
        "role": "Role",
        
        # Sales
        "sales_screen": "Sales Screen",
        "barcode_scanner": "Barcode Scanner:",
        "scan_barcode": "Scan or enter barcode",
        "scan_product_placeholder": "Scan Product Barcode...",
        "product": "Product",
        "quantity": "Qty",
        "unit_price": "Unit Price",
        "total": "Total ₺",
        "payment_method": "Payment Method",
        "choose_payment": "Choose payment method:",
        "cash": "Cash",
        "credit_card": "Credit Card",
        "customer_name": "Customer Name:",
        "add_to_cart": "Add to Cart",
        "remove_selected": "Remove Selected",
        "clear_cart": "Clear Cart",
        "complete_sale": "Complete Sale",
        "receipt_no": "Receipt No:",
        "discount": "Discount (%):",
        "vat": "VAT (%):",
        "vat_included": "VAT Included",
        "subtotal": "Subtotal:",
        "grand_total": "Grand Total:",
        "cancel_sale": "Cancel Sale",
        "recent_receipts": "Recent Receipts",
        "cancel_receipt": "Cancel Receipt",
        "confirm_cancel_receipt": "Do you want to cancel this receipt?",
        "cancel_success": "Receipt canceled.",
        "cancel_error": "An error occurred during cancellation.",
        
        # Receipts
        "receipts_title": "Saved Receipts (PDF)",
        "file": "File",
        "date": "Date",
        "open_print": "Open / Print",
        
        # Reports
        "reports_title": "Sales Report",
        "start_date": "Start Date (YYYY-MM-DD):",
        "end_date": "End Date (YYYY-MM-DD):",
        "export_csv": "Export CSV",
        
        # Accounts
        "cari_management": "Account Management",
    "cari_info": "Account Info",
        "cari_name": "Account Name:",
        "phone": "Phone:",
        "address": "Address:",
        "balance": "Balance:",
        "cari_type": "Type:",
        "alacakli": "Receivable",
        "borclu": "Payable",
        "tahsilat": "Collection",
        "odeme": "Payment",
        "borc": "Debt",
        "alacak": "Receivable",
        "tutar": "Amount:",
        "aciklama": "Description:",
        "hareketler": "Transactions",
        "islem_type": "Transaction",
        "total_alacak": "Total Receivable:",
        "total_borc": "Total Payable:",
        "add_tahsilat": "Add Collection",
        "add_odeme": "Add Payment",
        
        # Messages
        "warning": "Warning",
        "error": "Error",
        "success": "Success",
        "confirm": "Confirm",
        "select_item": "Please select an item.",
        "login_error": "Invalid username or password!",
        "delete_confirm": "Delete?",
        "receipt_created": "Receipt Created",
        "receipt_saved": "Invoice saved:",
        "report_saved": "Report Saved",
        "thank_you": "Thank you - SmartPOS Mini Pro",
        "copyright": "SmartPOS Mini Pro © 2025",
        "timestamp": "Timestamp:",
    "session": "Session",
        
        # Dialog
        "add_product": "Add Product",
        "product_name": "Product name:",
        "price_input": "Price (e.g. 99.90):",
        "stock_input": "Stock (e.g. 10):",
        "edit": "Edit",
        "new_user": "New User",
        "role_input": "Role (admin/cashier):",
        "new_password": "New password (leave empty=no change):",
        "duplicate_error": "This product name already exists!",
        "duplicate_user_error": "This username already exists!",
        "admin_delete_error": "Cannot delete admin user!",
        "enter_valid": "Please enter valid price/stock.",
        "customer": "Customer",
    "valid_product_qty": "Enter a valid product and quantity.",
    "product_not_found": "Product not found.",
    "insufficient_stock": "Insufficient stock! (Available: {stock})",
    "barcode_not_found": "Barcode not found: {barcode}",
    "cart_empty": "Cart is empty.",
    "info": "Info",
    "no_sales_today": "No sales for today.",
    "open_failed": "Could not open:",
    "date_format_warning": "Date format must be YYYY-MM-DD.",
    "daily_report_saved": "Daily report saved:",
    "csv_receipt_no": "Receipt No",
    "csv_product": "Product",
    "csv_qty": "Qty",
    "csv_price": "Price",
    "csv_total": "Total",
    "csv_date": "Date",
    "special_vat": "Custom VAT",
    "enter_vat_percent": "Enter VAT rate (%):",
    "no_sales_in_range": "No sales in this range.",
    "cari_added": "Account added",
    "cari_updated": "Account updated",
    "cari_deleted": "Account deleted",
    "cari_added_name": "Account added: {name}",
    "list": "List",
    "seq": "No",
    "vat_short": "VAT",

    # New Menu Items
    "dispatch_entry": "Dispatch Entry",
    "invoice_entry": "Invoice Entry",
    "stock_list": "Stock List",
    "dispatch_entry_coming": "Dispatch entry screen is coming soon.",
    "invoice_entry_coming": "Invoice entry screen is coming soon.",
    "coming_soon": "Coming soon.",
    "service_name": "Service Name",
    "new_service": "New Service",
    "expense_title": "Expense Title",
    "recent_expenses": "Recent Expenses",
    "saved": "Saved",
    "confirm_delete": "Are you sure you want to delete?",
    "amount": "Amount",
    "description": "Description",
        
        # PDF Receipt
        "receipt_header": "SMARTPOS MINI PRO - SALES RECEIPT",
        "receipt_customer": "Customer:",
        "receipt_date": "Date:",
        "receipt_product": "Product",
    "receipt_quantity": "Qty",
    "quantity_unit": "Quantity",
        "receipt_price": "Price",
        "receipt_total": "Amount",
        "receipt_subtotal": "Subtotal:",
        "receipt_discount": "Discount",
        "receipt_vat": "VAT",
        "receipt_grand_total": "Grand Total:",
        "receipt_thank_you": "Thank you - SmartPOS Mini Pro",
        
        # Thermal Printer
        "print_receipt": "Print Receipt",
        "print_options": "Choose printing option:",
        "thermal_printer": "Thermal Printer",
        "no_print": "No Print",
        "printer_setup": "Printer Setup",
        "enter_printer_name": "Enter printer name (check Devices and Printers):",
        "receipt_printed": "Receipt sent to printer!",
        "print_error": "Printer error",

        # Other
        "confirm_repeat": "Do you want to proceed with repeat?",
        "yes": "Yes",
        "no": "No",
        "all": "All",

        # Report Additions
        "total_stock": "Total Stock",
        "cost_value": "Cost Value",
        "sales_value": "Sales Value",
        "estimated_profit": "Estimated Profit",
        "total_cost": "Total Cost",
        "total_sales": "Total Sales",
        "total_receivable_market": "Total Receivable (Market)",
        "total_debt_ours": "Total Debt (Ours)",
        "net_status": "Net Status",
        "we_are_creditor": "(Creditor)",
        "we_are_debtor": "(Debtor)",
        "status": "Status",
        "debtor_to_us": "Debtor (To Us)",
        "creditor_from_us": "Creditor (From Us)",

        # Cash Report
        "cash_report_title": "CASH REPORT",
        "date_range": "Date Range",
        "total_sales_cash": "Total Sales (Cash)",
        "total_collection": "Total Collection",
        "total_inflow": "TOTAL INFLOW",
        "total_payment": "Total Payment",
        "total_expense": "Total Expense",
        "total_outflow": "TOTAL OUTFLOW",
        "net_balance_cap": "NET BALANCE",
        "report_btn": "Report",

        # Cash Movements & Closure
        "total_in_lbl": "Inflow",
        "total_out_lbl": "Outflow",
        "balance_lbl": "Balance",
        "date_lbl": "Date",
        "end_day_balance": "End of Day Balance",
        "close_day_btn": "CLOSE DAY",
        "close_day_success": "Cash closure completed successfully.\n\nClosing Balance",
    }
}
